version: "3.8"

services:
  app:
    build: 
      context: .
      args:
        APP_MODE: docker
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: peak-test
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
